# -------------------------------------------------------------------------------- load data
setwd(paste(project_folder, "Source data - not tracked", sep = ""))

folder.contents <- data.frame(list.files(path = getwd()))

folder.contents <- list.files(path = getwd())
for (i in 1:length(folder.contents)) assign(folder.contents[i], read.csv(folder.contents[i], header = FALSE, stringsAsFactors = FALSE, fileEncoding = "latin1", strip.white = TRUE))

# clean up environment
rm(folder.contents, i)

# these source tables are generated by:
# opening the source tab in the borrowing and investment series
# transpose/paste-as-values into a new sheet
# no other changes

# clean each table - assign column names, then drop unwanted rows from the top
Debt_0809.csv <- Debt_0809.csv %>% `colnames<-`(c(slice(Debt_0809.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_0910.csv <- Debt_0910.csv %>% `colnames<-`(c(slice(Debt_0910.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1011.csv <- Debt_1011.csv %>% `colnames<-`(c(slice(Debt_1011.csv, 2))) %>% slice(-1:-4) %>% clean_names()
Debt_1112.csv <- Debt_1112.csv %>% `colnames<-`(c(slice(Debt_1112.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1213.csv <- Debt_1213.csv %>% `colnames<-`(c(slice(Debt_1213.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1314.csv <- Debt_1314.csv %>% `colnames<-`(c(slice(Debt_1314.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1415.csv <- Debt_1415.csv %>% `colnames<-`(c(slice(Debt_1415.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1516.csv <- Debt_1516.csv %>% `colnames<-`(c(slice(Debt_1516.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1617_Q3.csv <- Debt_1617_Q3.csv %>% `colnames<-`(c(slice(Debt_1617_Q3.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1617_Q4.csv <- Debt_1617_Q4.csv %>% `colnames<-`(c(slice(Debt_1617_Q4.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1718_Q1.csv <- Debt_1718_Q1.csv %>% `colnames<-`(c(slice(Debt_1718_Q1.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1718_Q2.csv <- Debt_1718_Q2.csv %>% `colnames<-`(c(slice(Debt_1718_Q2.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1718_Q3.csv <- Debt_1718_Q3.csv %>% `colnames<-`(c(slice(Debt_1718_Q3.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1718_Q4.csv <- Debt_1718_Q4.csv %>% `colnames<-`(c(slice(Debt_1718_Q4.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1819_Q1.csv <- Debt_1819_Q1.csv %>% `colnames<-`(c(slice(Debt_1819_Q1.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1819_Q2.csv <- Debt_1819_Q2.csv %>% `colnames<-`(c(slice(Debt_1819_Q2.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1819_Q3.csv <- Debt_1819_Q3.csv %>% `colnames<-`(c(slice(Debt_1819_Q3.csv, 2))) %>% slice(-1:-3) %>% clean_names()
Debt_1819_Q4.csv <- Debt_1819_Q4.csv %>% `colnames<-`(c(slice(Debt_1819_Q4.csv, 2))) %>% slice(-1:-2) %>% clean_names()
Debt_1920_Q1.csv <- Debt_1920_Q1.csv %>% `colnames<-`(c(slice(Debt_1920_Q1.csv, 2))) %>% slice(-1:-3) %>% clean_names()
Debt_1920_Q2.csv <- Debt_1920_Q2.csv %>% `colnames<-`(c(slice(Debt_1920_Q2.csv, 2))) %>% slice(-1:-3) %>% clean_names()

# reshape to long format and date
Debt_0809.csv <- Debt_0809.csv %>% gather(LA, Value, 2:ncol(Debt_0809.csv)) %>% mutate(Date = as.Date("2009/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_0910.csv <- Debt_0910.csv %>% gather(LA, Value, 2:ncol(Debt_0910.csv)) %>% mutate(Date = as.Date("2010/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1011.csv <- Debt_1011.csv %>% gather(LA, Value, 2:ncol(Debt_1011.csv)) %>% mutate(Date = as.Date("2011/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1112.csv <- Debt_1112.csv %>% gather(LA, Value, 2:ncol(Debt_1112.csv)) %>% mutate(Date = as.Date("2012/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1213.csv <- Debt_1213.csv %>% gather(LA, Value, 2:ncol(Debt_1213.csv)) %>% mutate(Date = as.Date("2013/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1314.csv <- Debt_1314.csv %>% gather(LA, Value, 2:ncol(Debt_1314.csv)) %>% mutate(Date = as.Date("2014/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1415.csv <- Debt_1415.csv %>% gather(LA, Value, 2:ncol(Debt_1415.csv)) %>% mutate(Date = as.Date("2015/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1516.csv <- Debt_1516.csv %>% gather(LA, Value, 2:ncol(Debt_1516.csv)) %>% mutate(Date = as.Date("2016/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1617_Q3.csv <- Debt_1617_Q3.csv %>% gather(LA, Value, 2:ncol(Debt_1617_Q3.csv)) %>% mutate(Date = as.Date("2016/12/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1617_Q4.csv <- Debt_1617_Q4.csv %>% gather(LA, Value, 2:ncol(Debt_1617_Q4.csv)) %>% mutate(Date = as.Date("2017/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1718_Q1.csv <- Debt_1718_Q1.csv %>% gather(LA, Value, 2:ncol(Debt_1718_Q1.csv)) %>% mutate(Date = as.Date("2017/06/30", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1718_Q2.csv <- Debt_1718_Q2.csv %>% gather(LA, Value, 2:ncol(Debt_1718_Q2.csv)) %>% mutate(Date = as.Date("2017/09/30", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1718_Q3.csv <- Debt_1718_Q3.csv %>% gather(LA, Value, 2:ncol(Debt_1718_Q3.csv)) %>% mutate(Date = as.Date("2017/12/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority)
Debt_1718_Q4.csv <- Debt_1718_Q4.csv %>% gather(LA, Value, 2:ncol(Debt_1718_Q4.csv)) %>% mutate(Date = as.Date("2018/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority_name)
Debt_1819_Q1.csv <- Debt_1819_Q1.csv %>% gather(LA, Value, 2:ncol(Debt_1819_Q1.csv)) %>% mutate(Date = as.Date("2018/06/30", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority_name)
Debt_1819_Q2.csv <- Debt_1819_Q2.csv %>% gather(LA, Value, 2:ncol(Debt_1819_Q2.csv)) %>% mutate(Date = as.Date("2018/09/30", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority_name) 
Debt_1819_Q3.csv <- Debt_1819_Q3.csv %>% gather(LA, Value, 2:ncol(Debt_1819_Q3.csv)) %>% mutate(Date = as.Date("2018/12/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority_name)  
Debt_1819_Q4.csv <- Debt_1819_Q4.csv %>% gather(LA, Value, 2:ncol(Debt_1819_Q4.csv)) %>% mutate(Date = as.Date("2019/03/31", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority_name) 
Debt_1920_Q1.csv <- Debt_1920_Q1.csv %>% gather(LA, Value, 2:ncol(Debt_1920_Q1.csv)) %>% mutate(Date = as.Date("2019/06/30", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority_name) 
Debt_1920_Q2.csv <- Debt_1920_Q2.csv %>% gather(LA, Value, 2:ncol(Debt_1920_Q2.csv)) %>% mutate(Date = as.Date("2019/09/30", format = "%Y/%m/%d")) %>% rename(Debt_type = local_authority_name)

# stack and tidy up
Debt <- bind_rows(Debt_0809.csv, Debt_0910.csv, Debt_1011.csv, Debt_1112.csv, Debt_1213.csv, Debt_1314.csv, Debt_1415.csv, Debt_1516.csv, Debt_1617_Q3.csv, Debt_1617_Q4.csv, Debt_1718_Q1.csv, Debt_1718_Q2.csv, Debt_1718_Q3.csv, Debt_1718_Q4.csv, Debt_1819_Q1.csv, Debt_1819_Q2.csv, Debt_1819_Q3.csv, Debt_1819_Q4.csv, Debt_1920_Q1.csv, Debt_1920_Q2.csv) %>%
	filter(!Debt_type %in% c("Country","Class of authority", "ONS code")) %>%
		mutate(
		Value = as.numeric(Value),
		Value = Value/ 1000,
		Units = "GPBmillion",
		LA = as.factor(LA),
		Units = as.factor(Units))

rm(Debt_0809.csv, Debt_0910.csv, Debt_1011.csv, Debt_1112.csv, Debt_1213.csv, Debt_1314.csv, Debt_1415.csv, Debt_1516.csv, Debt_1617_Q3.csv, Debt_1617_Q4.csv, Debt_1718_Q1.csv, Debt_1718_Q2.csv, Debt_1718_Q3.csv, Debt_1718_Q4.csv, Debt_1819_Q1.csv, Debt_1819_Q2.csv, Debt_1819_Q3.csv, Debt_1819_Q4.csv, Debt_1920_Q1.csv, Debt_1920_Q2.csv)

# -------------------------------------------------------------------------------- tidy up and write out
#write out
setwd(paste(project_folder, "Intermediate outputs", sep = ""))

#Debt <- Debt %>% spread(Date, Value)

ifelse(write_out_y_n == "y", write.csv(Debt, file = "01 stack debt.csv", row.names = FALSE), "")


